name: Docker Stacks

# [FAST_BUILD] in the PR title makes this workflow only build
# the `jupyter/docker-stacks-foundation` and `jupyter/base-notebook` images
# This allows to run CI faster if a full build is not required
# This only works for a `pull_request` event and does not affect `push` to the `main` branch

on:
  schedule:
    # Weekly, at 03:00 on Monday UTC
    - cron: "0 3 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      # We use local reusable workflows to make architecture clean and simple
      # https://docs.github.com/en/actions/sharing-automations/reusing-workflows
      - ".github/workflows/docker-build-test-upload.yml"
      - ".github/workflows/docker-tag-push.yml"
      - ".github/workflows/docker-apptainer-push.yml"
      - ".github/workflows/docker-wiki-update.yml"

      # We use local composite actions to combine multiple workflow steps within one action
      # https://docs.github.com/en/actions/sharing-automations/creating-actions/about-custom-actions#composite-actions
      - ".github/actions/apply-single-tags/action.yml"
      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/load-image/action.yml"

      - "images/**"
      - "!images/*/README.md"
      - "tagging/**"
      - "!tagging/README.md"
      - "tests/**"
      - "!tests/README.md"
      - "wiki/**"
      - "requirements-dev.txt"

  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - ".github/workflows/docker-build-test-upload.yml"
      - ".github/workflows/docker-tag-push.yml"
      - ".github/workflows/docker-apptainer-push.yml"
      - ".github/workflows/docker-wiki-update.yml"

      - ".github/actions/apply-single-tags/action.yml"
      - ".github/actions/create-dev-env/action.yml"
      - ".github/actions/load-image/action.yml"

      - "images/**"
      - "!images/*/README.md"
      - "tagging/**"
      - "!tagging/README.md"
      - "tests/**"
      - "!tests/README.md"
      - "wiki/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  # Only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  aarch64-datascience:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: ""
      image: datascience-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 25

  x86_64-datascience:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: ""
      image: datascience-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 25

  aarch64-sequencing-base:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: datascience-notebook
      image: sequencing-base-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 25
    needs: aarch64-datascience

  x86_64-sequencing-base:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: datascience-notebook
      image: sequencing-base-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 25
    needs: x86_64-datascience

  aarch64-rnaseq:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: sequencing-base-notebook
      image: rnaseq-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 30
    needs: aarch64-sequencing-base
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-rnaseq:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: sequencing-base-notebook
      image: rnaseq-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 45
    needs: x86_64-sequencing-base
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  aarch64-singlecell:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: sequencing-base-notebook
      image: singlecell-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 40
    needs: aarch64-sequencing-base
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-singlecell:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: sequencing-base-notebook
      image: singlecell-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 40
    needs: x86_64-sequencing-base
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  aarch64-multiomics:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: singlecell-notebook
      image: multiomics-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 40
    needs: aarch64-singlecell
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-multiomics:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: singlecell-notebook
      image: multiomics-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 40
    needs: x86_64-singlecell
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  aarch64-spatial:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: singlecell-notebook
      image: spatial-notebook
      platform: aarch64
      runs-on: ubuntu-24.04-arm
      timeout-minutes: 40
    needs: aarch64-singlecell
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  x86_64-spatial:
    uses: ./.github/workflows/docker-build-test-upload.yml
    with:
      parent-image: singlecell-notebook
      image: spatial-notebook
      platform: x86_64
      runs-on: ubuntu-24.04
      timeout-minutes: 40
    needs: x86_64-singlecell
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  contributed-recipes:
    uses: ./.github/workflows/contributed-recipes.yml
    with:
      called-using-workflow-call: true
    # Contributed recipes only use these images
    # If recipes using other images will be added, they should be added here as well
    #
    # contributed-recipes will give an error if the image is not yet built and uploaded
    # prettier-ignore
    needs:
      [
        aarch64-datascience,
        x86_64-datascience,
        aarch64-sequencing-base,
        x86_64-sequencing-base,
      ]

  tag-push:
    uses: ./.github/workflows/docker-tag-push.yml
    with:
      image: ${{ matrix.image }}
      variant: ${{ matrix.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
    strategy:
      matrix:
        # prettier-ignore
        image:
          [
            datascience-notebook,
            sequencing-base-notebook,
            rnaseq-notebook,
            singlecell-notebook,
            multiomics-notebook,
            spatial-notebook,
          ]
        variant: [default]
    # prettier-ignore
    needs:
      [
        contributed-recipes,

        aarch64-datascience,
        aarch64-sequencing-base,
        aarch64-rnaseq,
        aarch64-singlecell,
        aarch64-multiomics,
        aarch64-spatial,

        x86_64-datascience,
        x86_64-sequencing-base,
        x86_64-rnaseq,
        x86_64-singlecell,
        x86_64-multiomics,
        x86_64-spatial,
      ]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  tag-push-fast:
    uses: ./.github/workflows/docker-tag-push.yml
    with:
      image: ${{ matrix.image }}
      variant: ${{ matrix.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
    strategy:
      matrix:
        image: [datascience-notebook, sequencing-base-notebook]
        variant: [default]
    # prettier-ignore
    needs:
      [
        aarch64-datascience,
        x86_64-datascience,
        aarch64-sequencing-base,
        x86_64-sequencing-base,
      ]
    if: contains(github.event.pull_request.title, '[FAST_BUILD]')

  apptainer-push:
    uses: ./.github/workflows/docker-apptainer-push.yml
    with:
      image: ${{ matrix.image }}
      variant: ${{ matrix.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
    strategy:
      matrix:
        # prettier-ignore
        image:
          [
            datascience-notebook,
            sequencing-base-notebook,
            rnaseq-notebook,
            singlecell-notebook,
            multiomics-notebook,
            spatial-notebook,
          ]
        variant: [default]
    # Depends on build jobs, not tag-push (build jobs generate tag artifacts)
    # prettier-ignore
    needs:
      [
        aarch64-datascience,
        x86_64-datascience,
        aarch64-sequencing-base,
        x86_64-sequencing-base,
        aarch64-rnaseq,
        x86_64-rnaseq,
        aarch64-singlecell,
        x86_64-singlecell,
        aarch64-multiomics,
        x86_64-multiomics,
        aarch64-spatial,
        x86_64-spatial,
      ]
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}

  apptainer-push-fast:
    uses: ./.github/workflows/docker-apptainer-push.yml
    with:
      image: ${{ matrix.image }}
      variant: ${{ matrix.variant }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
    strategy:
      matrix:
        image: [datascience-notebook, sequencing-base-notebook]
        variant: [default]
    # Depends on build jobs, not tag-push-fast (build jobs generate tag artifacts)
    # prettier-ignore
    needs:
      [
        aarch64-datascience,
        x86_64-datascience,
        aarch64-sequencing-base,
        x86_64-sequencing-base,
      ]
    if: contains(github.event.pull_request.title, '[FAST_BUILD]')

  wiki-update:
    uses: ./.github/workflows/docker-wiki-update.yml
    needs: tag-push
    if: ${{ !contains(github.event.pull_request.title, '[FAST_BUILD]') }}
    permissions:
      contents: write

  wiki-update-fast:
    uses: ./.github/workflows/docker-wiki-update.yml
    needs: tag-push-fast
    if: contains(github.event.pull_request.title, '[FAST_BUILD]')
    permissions:
      contents: write
